version: 1.0
deploy:
  # comment in one of the following lines to force the use of the recurring or bootstrap configuration
  #  force: recurring
  #  force: bootstrap

  # configure the initial deployment of each branch
  bootstrap:
    # directories that are not overwritten or removed by the next deployment
    excludes:
      - tests
      - node_modules
      # the following three files are generated during composer action and are not neccessary
      - DOCKER_ENV
      - docker_tag
      - output.log
      - Dockerfile-php-build
      - .template-renderer-data

    # commands that are executed on the runtime after new files are copied
    post-deployment-remote-commands:
      # set right file permissions for Laravel
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      # migrate database, clear caches, migrate database, link storage, warmup caches
      - php artisan migrate --force
      - php artisan optimize:clear
      - php artisan migrate --force -n
      - php artisan storage:link
      - php artisan optimize
      - php artisan up

  # configure all following deployments of each branch
  recurring:
    # directories that are not overwritten or removed by the next deployment
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - Dockerfile-php-build
      - .template-renderer-data
      # the storage folder shouldn't be synced after first deployment, because there
      # are files inside from running the Laravel app (e.g. database)
      - storage

    # commands that are executed on the runtime before new files are copied
    pre-deployment-remote-commands:
      - php artisan down

    # commands that are executed on the runtime after new files are copied
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - php artisan migrate --force
      - php artisan optimize:clear
      - php artisan migrate --force -n
      - php artisan storage:link
      - php artisan optimize
      - php artisan up
